[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
bonding_curve = "J8bgMduAt7kgqN4htuCU2WwHEuPNPWnxGkNLe2kiCwyq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test-watch = "fswatch -o ./programs ./tests ./Anchor.toml | xargs -n1 -I{} anchor test"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/metaplex_metadata.so"